export const countries = [
  { name: "India", code: "+91", flag: "🇮🇳", length: 10 },
  { name: "United States", code: "+1", flag: "🇺🇸", length: 10 },
  { name: "United Kingdom", code: "+44", flag: "🇬🇧", length: 10 },
  { name: "Canada", code: "+1", flag: "🇨🇦", length: 10 },
  { name: "Australia", code: "+61", flag: "🇦🇺", length: 9 },
  { name: "Germany", code: "+49", flag: "🇩🇪", length: 11 },
  { name: "France", code: "+33", flag: "🇫🇷", length: 9 },
  { name: "UAE", code: "+971", flag: "🇦🇪", length: 9 },
  { name: "Singapore", code: "+65", flag: "🇸🇬", length: 8 },
  { name: "Japan", code: "+81", flag: "🇯🇵", length: 10 },
  { name: "South Korea", code: "+82", flag: "🇰🇷", length: 10 },
  { name: "Brazil", code: "+55", flag: "🇧🇷", length: 11 },
  { name: "Mexico", code: "+52", flag: "🇲🇽", length: 10 },
  { name: "South Africa", code: "+27", flag: "🇿🇦", length: 9 },
  { name: "Nigeria", code: "+234", flag: "🇳🇬", length: 10 },
  { name: "Saudi Arabia", code: "+966", flag: "🇸🇦", length: 9 },
  { name: "Qatar", code: "+974", flag: "🇶🇦", length: 8 },
  { name: "Kuwait", code: "+965", flag: "🇰🇼", length: 8 },
  { name: "Oman", code: "+968", flag: "🇴🇲", length: 8 },
  { name: "Bahrain", code: "+973", flag: "🇧🇭", length: 8 },
  { name: "Malaysia", code: "+60", flag: "🇲🇾", length: 10 },
  { name: "Indonesia", code: "+62", flag: "🇮🇩", length: 10 },
  { name: "Thailand", code: "+66", flag: "🇹🇭", length: 9 },
  { name: "Vietnam", code: "+84", flag: "🇻🇳", length: 9 },
  { name: "Philippines", code: "+63", flag: "🇵🇭", length: 10 },
  { name: "Italy", code: "+39", flag: "🇮🇹", length: 10 },
  { name: "Spain", code: "+34", flag: "🇪🇸", length: 9 },
  { name: "Netherlands", code: "+31", flag: "🇳🇱", length: 9 },
  { name: "Turkey", code: "+90", flag: "🇹🇷", length: 10 },
  { name: "Egypt", code: "+20", flag: "🇪🇬", length: 10 },
  { name: "Kenya", code: "+254", flag: "🇰🇪", length: 9 },
  { name: "Argentina", code: "+54", flag: "🇦🇷", length: 10 },
];

export const businessCategories = [
  "Food",
  "Grocery",
  "Cloth",
  "Electronics",
  "Pharmacy",
];
