/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserLinksRouteImport } from './routes/user-links'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterBusinessRouteImport } from './routes/register-business'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ConnectDomainRouteImport } from './routes/connect-domain'
import { Route as IndexRouteImport } from './routes/index'

const UserLinksRoute = UserLinksRouteImport.update({
  id: '/user-links',
  path: '/user-links',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterBusinessRoute = RegisterBusinessRouteImport.update({
  id: '/register-business',
  path: '/register-business',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectDomainRoute = ConnectDomainRouteImport.update({
  id: '/connect-domain',
  path: '/connect-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-domain': typeof ConnectDomainRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register-business': typeof RegisterBusinessRoute
  '/signup': typeof SignupRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/user-links': typeof UserLinksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-domain': typeof ConnectDomainRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register-business': typeof RegisterBusinessRoute
  '/signup': typeof SignupRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/user-links': typeof UserLinksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-domain': typeof ConnectDomainRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register-business': typeof RegisterBusinessRoute
  '/signup': typeof SignupRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/user-links': typeof UserLinksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect-domain'
    | '/privacy-policy'
    | '/register-business'
    | '/signup'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/user-links'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-domain'
    | '/privacy-policy'
    | '/register-business'
    | '/signup'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/user-links'
  id:
    | '__root__'
    | '/'
    | '/connect-domain'
    | '/privacy-policy'
    | '/register-business'
    | '/signup'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/user-links'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectDomainRoute: typeof ConnectDomainRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterBusinessRoute: typeof RegisterBusinessRoute
  SignupRoute: typeof SignupRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ThankYouRoute: typeof ThankYouRoute
  UserLinksRoute: typeof UserLinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-links': {
      id: '/user-links'
      path: '/user-links'
      fullPath: '/user-links'
      preLoaderRoute: typeof UserLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-business': {
      id: '/register-business'
      path: '/register-business'
      fullPath: '/register-business'
      preLoaderRoute: typeof RegisterBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-domain': {
      id: '/connect-domain'
      path: '/connect-domain'
      fullPath: '/connect-domain'
      preLoaderRoute: typeof ConnectDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectDomainRoute: ConnectDomainRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterBusinessRoute: RegisterBusinessRoute,
  SignupRoute: SignupRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ThankYouRoute: ThankYouRoute,
  UserLinksRoute: UserLinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
